name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      -  name: Checkout source
         uses: actions/checkout@v4
      -  name: Setup Node.js
         uses: actions/setup-node@v4
         with:
           node-version: '18.x'
      -  name: Install dependencies
         run: npm install
      -  name: Run test
         run: npm test
      -  name: Deploy to Azure Web App
         uses: azure/webapps-deploy@v2
         with:
           app-name: githubActionsDemoWebApp
           publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
           package: .
